Fix type branding
The branding of `Calendar*` and `Timestamp` doesn't work correctly:
assignments like this are allowed by the type system:
```
const month: CalendarMonth = toUtcDay("foo");
```

This is because `enum {} & string` is like `number & string`, which
evaluates to `never`.  So we need to find a different way to brand these
types.

This solution, using a class with a protected member variable, is the best
that I've found.  The protected member variable means that no additional
properties are visible on the type (you aren't allowed to access
`month._brand_`).  The main downside is that this introduces an additional
class.  I think it's worth the small code size increase.

Note that the TypeScript error messages are still easy to understand.  For
example, if you try to do this:
```
const duration: DurationMs = toUtcDay("foo");
const month: CalendarMonth = toUtcDay("foo");
```
you get the following errors:
```
test/NomDate.test.ts:99:7 - error TS2322: Type 'CalendarDay' is not assignable to type 'CalendarMonth'.
  Type 'CalendarDay' is not assignable to type 'Brand<"CalendarMonth">'.
    Types of property '_brand_' are incompatible.
      Type '"CalendarDay"' is not assignable to type '"CalendarMonth"'.

99 const month: CalendarMonth = toUtcDay("foo");
         ~~~~~

test/NomDate.test.ts:100:7 - error TS2322: Type 'CalendarDay' is not assignable to type 'DurationMs'.
  Type 'CalendarDay' is not assignable to type 'number'.

100 const duration: DurationMs = toUtcDay("foo");
          ~~~~~~~~
```

Test Plan:
Ran `yarn prepack`.  `NomDate.test.ts` passed.

Used `yarn link` to link this module into `covid-19/server/functions`.
Checked that this generates a type error:
```
const month: CalendarMonth = toUtcDay("foo");
```